<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>KvmSwitch.Regression.Program</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\src\*.cs" Link="App\%(Filename)%(Extension)" />
  </ItemGroup>
</Project>

